import { TUsageGraphCardDatum } from '../../types/UsageGraphCard'

export const DEFAULT_SERIES: TUsageGraphCardDatum[] = [
  { value: 22 },
  { value: 30 },
  { value: 26 },
  { value: 28 },
  { value: 24 },
  { value: 31 },
  { value: 27 },
  { value: 29 },
  { value: 25 },
  { value: 33 },
  { value: 28 },
  { value: 26 },
  { value: 30 },
  { value: 27 },
  { value: 32 },
  { value: 35 },
  { value: 31 },
  { value: 38 },
  { value: 29 },
  { value: 34 },
  { value: 30 },
  { value: 28 },
  { value: 33 },
  { value: 31 },
  { value: 36 },
  { value: 29 },
  { value: 32 },
  { value: 30 },
  { value: 34 },
  { value: 31 },
]
